"""Added BillInfo table

Revision ID: 55435165bb6f
Revises: cd29bf4f8a3b
Create Date: 2025-07-27 10:33:21.682206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55435165bb6f'
down_revision: Union[str, None] = 'cd29bf4f8a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_info', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_info', 'status')
    # ### end Alembic commands ###
