"""Added BillInfo table

Revision ID: 5b7483e1dd7b
Revises: c72c1a5c542e
Create Date: 2025-07-31 18:13:15.283997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b7483e1dd7b'
down_revision: Union[str, None] = 'c72c1a5c542e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'reason_for_visit',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('appointments', 'appointment_type',
               existing_type=postgresql.ENUM('new', 'follow_up', 'online', 'emergency', name='appointmenttypeenum'),
               nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='statusenum'),
               nullable=True)
    op.alter_column('appointments', 'payment_status',
               existing_type=postgresql.ENUM('paid', 'unpaid', 'partial', name='paymentstatusenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'payment_status',
               existing_type=postgresql.ENUM('paid', 'unpaid', 'partial', name='paymentstatusenum'),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='statusenum'),
               nullable=False)
    op.alter_column('appointments', 'appointment_type',
               existing_type=postgresql.ENUM('new', 'follow_up', 'online', 'emergency', name='appointmenttypeenum'),
               nullable=False)
    op.alter_column('appointments', 'reason_for_visit',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
