"""create visit service table

Revision ID: 7e6bf791fd87
Revises: 2cf16123b0f6
Create Date: 2025-07-26 15:06:54.151043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6bf791fd87'
down_revision: Union[str, None] = '2cf16123b0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('visit_services_purchased_billed_id_key'), 'visit_services', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('visit_services_purchased_billed_id_key'), 'visit_services', ['purchased_billed_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
