"""Added BillInfo table

Revision ID: aebfef8c4cd4
Revises: 55435165bb6f
Create Date: 2025-07-28 08:29:56.024729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebfef8c4cd4'
down_revision: Union[str, None] = '55435165bb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bill_info_visit_id_key'), 'bill_info', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('bill_info_visit_id_key'), 'bill_info', ['visit_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
