"""create patient and appointment changes

Revision ID: c72c1a5c542e
Revises: aebfef8c4cd4
Create Date: 2025-07-31 10:05:45.730502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72c1a5c542e'
down_revision: Union[str, None] = 'aebfef8c4cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('patients', 'emergency_contact_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'emergency_contact_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
