"""Added BillInfo table

Revision ID: cd29bf4f8a3b
Revises: c708b6051325
Create Date: 2025-07-27 10:28:22.707350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd29bf4f8a3b'
down_revision: Union[str, None] = 'c708b6051325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('purchased_billed_id', sa.String(), nullable=True),
    sa.Column('total_bill_amount', sa.Integer(), nullable=False),
    sa.Column('pay_bill_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchased_billed_id'),
    sa.UniqueConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_info')
    # ### end Alembic commands ###
