"""Add visit_status to Visits

Revision ID: d27974a2d4a3
Revises: 6ecc4cc7bd0a
Create Date: 2025-06-25 18:57:04.012130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd27974a2d4a3'
down_revision: Union[str, None] = '6ecc4cc7bd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'visit_status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='statusenum'),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'visit_status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'completed', name='statusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
