"""Create services table

Revision ID: e4289647781a
Revises: ad5dfc22ab20
Create Date: 2025-06-27 18:56:15.358535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4289647781a'
down_revision: Union[str, None] = 'ad5dfc22ab20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_services', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('visit_services', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_services', 'quantity')
    op.drop_column('visit_services', 'price')
    # ### end Alembic commands ###
