"""Add is_billed, is_paid, and purchased_billed_id to visit_services

Revision ID: edc4e7b6810b
Revises: 026537f99b1f
Create Date: 2025-07-09 16:03:23.796153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc4e7b6810b'
down_revision: Union[str, None] = '026537f99b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_services', sa.Column('is_billed', sa.Boolean(), nullable=True))
    op.add_column('visit_services', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('visit_services', sa.Column('purchased_billed_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'visit_services', ['purchased_billed_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_services', type_='unique')
    op.drop_column('visit_services', 'purchased_billed_id')
    op.drop_column('visit_services', 'is_paid')
    op.drop_column('visit_services', 'is_billed')
    # ### end Alembic commands ###
